import { useState, useEffect } from 'react';
import Markdown from 'react-markdown';
import { getStats } from '../api/oracle';
import styles from './Handoff.module.css';

interface SessionStats {
  searches: number;
  consultations: number;
  learnings: number;
  startTime: number;
}

export function Handoff() {
  const [stats, setStats] = useState<any>(null);
  const [sessionStats, setSessionStats] = useState<SessionStats | null>(null);
  const [markdown, setMarkdown] = useState('');
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(true);

  useEffect(() => {
    loadData();
    loadSessionStats();
  }, []);

  async function loadData() {
    try {
      const data = await getStats();
      setStats(data);
    } catch (e) {
      console.error('Failed to load stats:', e);
    }
  }

  function loadSessionStats() {
    const stored = localStorage.getItem('oracle_session');
    if (stored) {
      const parsed = JSON.parse(stored);
      // Validate startTime exists and is a valid number
      if (!parsed.startTime || isNaN(parsed.startTime)) {
        parsed.startTime = Date.now();
        localStorage.setItem('oracle_session', JSON.stringify(parsed));
      }
      setSessionStats(parsed);
    } else {
      const initial: SessionStats = {
        searches: 0,
        consultations: 0,
        learnings: 0,
        startTime: Date.now()
      };
      localStorage.setItem('oracle_session', JSON.stringify(initial));
      setSessionStats(initial);
    }
  }

  function generateHandoff() {
    const now = new Date();
    const duration = sessionStats
      ? Math.floor((Date.now() - sessionStats.startTime) / 60000)
      : 0;

    const md = `## Session Handoff

**Date**: ${now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
**Knowledge Base**: ${stats?.documents?.toLocaleString() || 0} documents, ${stats?.concepts || 0} concepts

### Activity Summary
- Searches: ${sessionStats?.searches || 0}
- Consultations: ${sessionStats?.consultations || 0}
- Learnings: ${sessionStats?.learnings || 0}
- Session Duration: ${duration} minutes

### Notes
_Add your session notes here..._

---
*Generated by Oracle Dashboard*`;

    setMarkdown(md);
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('Failed to copy:', e);
    }
  }

  function resetSession() {
    const initial: SessionStats = {
      searches: 0,
      consultations: 0,
      learnings: 0,
      startTime: Date.now()
    };
    localStorage.setItem('oracle_session', JSON.stringify(initial));
    setSessionStats(initial);
    setMarkdown('');
  }

  const duration = sessionStats
    ? Math.floor((Date.now() - sessionStats.startTime) / 60000)
    : 0;

  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Session Handoff</h1>
      <p className={styles.subtitle}>Generate a summary of your Oracle session</p>

      <div className={styles.statsGrid}>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{sessionStats?.searches || 0}</div>
          <div className={styles.statLabel}>Searches</div>
        </div>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{sessionStats?.consultations || 0}</div>
          <div className={styles.statLabel}>Consultations</div>
        </div>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{sessionStats?.learnings || 0}</div>
          <div className={styles.statLabel}>Learnings</div>
        </div>
        <div className={styles.statCard}>
          <div className={styles.statValue}>{duration}m</div>
          <div className={styles.statLabel}>Duration</div>
        </div>
      </div>

      <div className={styles.actions}>
        <button onClick={generateHandoff} className={styles.primaryBtn}>
          Generate Handoff
        </button>
        <button onClick={resetSession} className={styles.secondaryBtn}>
          Reset Session
        </button>
      </div>

      {markdown && (
        <div className={styles.output}>
          <div className={styles.outputHeader}>
            <div className={styles.tabs}>
              <button
                onClick={() => setShowPreview(true)}
                className={`${styles.tab} ${showPreview ? styles.activeTab : ''}`}
              >
                Preview
              </button>
              <button
                onClick={() => setShowPreview(false)}
                className={`${styles.tab} ${!showPreview ? styles.activeTab : ''}`}
              >
                Markdown
              </button>
            </div>
            <button onClick={copyToClipboard} className={styles.copyBtn}>
              {copied ? '✓ Copied!' : 'Copy'}
            </button>
          </div>
          {showPreview ? (
            <div className={styles.preview}>
              <Markdown>{markdown}</Markdown>
            </div>
          ) : (
            <pre className={styles.markdown}>{markdown}</pre>
          )}
        </div>
      )}
    </div>
  );
}
